// src/lib/locationData.ts

export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const countries: Country[] = [
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬' },
  { code: 'CD', name: 'Congo (Democratic Republic)', flag: '🇨🇩' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CI', name: 'Ivory Coast', flag: '🇨🇮' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸' },
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼' },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VA', name: 'Vatican City', flag: '🇻🇦' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' },
];

export const citiesByCountry: Record<string, string[]> = {
  'AF': ['Kabul', 'Herat', 'Kandahar', 'Mazar-i-Sharif', 'Jalalabad', 'Kunduz', 'Ghazni', 'Balkh', 'Baghlan', 'Gardez'],
  'AL': ['Tirana', 'Durrës', 'Vlorë', 'Elbasan', 'Shkodër', 'Kamëz', 'Fier', 'Korçë', 'Berat', 'Lushnjë'],
  'DZ': ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Djelfa', 'Sétif', 'Sidi Bel Abbès', 'Biskra'],
  'AD': ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'La Massana'],
  'AO': ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Kuito', 'Lubango', 'Malanje', 'Namibe', 'Soyo', 'Uíge'],
  'AG': ["Saint John's", 'All Saints', 'Liberta', 'Potters Village'],
  'AR': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Tucumán', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan'],
  'AM': ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Abovyan'],
  'AU': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Wollongong', 'Hobart'],
  'AT': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt'],
  'AZ': ['Baku', 'Ganja', 'Sumqayit', 'Mingaçevir', 'Lankaran'],
  'BS': ['Nassau', 'Lucaya', 'Freeport', 'West End'],
  'BH': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'A\'ali'],
  'BD': ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Gazipur', 'Narayanganj', 'Comilla', 'Rangpur', 'Barisal'],
  'BB': ['Bridgetown', 'Speightstown', 'Oistins', 'Holetown'],
  'BY': ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest'],
  'BE': ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges'],
  'BZ': ['Belize City', 'San Ignacio', 'Belmopan', 'Orange Walk Town', 'San Pedro'],
  'BJ': ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou', 'Bohicon'],
  'BT': ['Thimphu', 'Phuntsholing', 'Paro', 'Gelephu'],
  'BO': ['La Paz', 'Santa Cruz de la Sierra', 'Cochabamba', 'Sucre', 'Oruro'],
  'BA': ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar'],
  'BW': ['Gaborone', 'Francistown', 'Molepolole', 'Maun', 'Serowe'],
  'BR': ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'],
  'BN': ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong'],
  'BG': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora'],
  'BF': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya'],
  'BI': ['Bujumbura', 'Gitega', 'Ngozi', 'Rumonge'],
  'CV': ['Praia', 'Mindelo', 'Santa Maria', 'Assomada'],
  'KH': ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Poipet'],
  'CM': ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua'],
  'CA': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'London'],
  'CF': ['Bangui', 'Bimbo', 'Berbérati', 'Carnot'],
  'TD': ["N'Djamena", 'Moundou', 'Sarh', 'Abéché'],
  'CL': ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Temuco'],
  'CN': ['Shanghai', 'Beijing', 'Chongqing', 'Tianjin', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Nanjing', 'Wuhan', 'Hangzhou'],
  'CO': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Ibagué'],
  'KM': ['Moroni', 'Mutsamudu', 'Fomboni'],
  'CG': ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi'],
  'CD': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Bukavu', 'Goma', 'Likasi', 'Kolwezi', 'Masina'],
  'CR': ['San José', 'Limon', 'Alajuela', 'Heredia', 'Puntarenas'],
  'CI': ['Abidjan', 'Yamoussoukro', 'Bouaké', 'Daloa', 'San-Pédro'],
  'HR': ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar'],
  'CU': ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara'],
  'CY': ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Famagusta'],
  'CZ': ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec'],
  'DK': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'],
  'DJ': ['Djibouti', 'Ali Sabieh', 'Tadjoura', 'Obock'],
  'DM': ['Roseau', 'Portsmouth', 'Marigot', 'Berekua'],
  'DO': ['Santo Domingo', 'Santiago de los Caballeros', 'La Romana', 'San Pedro de Macorís', 'Higüey'],
  'EC': ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo', 'Machala'],
  'EG': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Mansoura', 'Tanta', 'Asyut'],
  'SV': ['San Salvador', 'Soyapango', 'Santa Ana', 'San Miguel', 'Mejicanos'],
  'GQ': ['Malabo', 'Bata', 'Ebebiyín', 'Aconibe'],
  'ER': ['Asmara', 'Keren', 'Massawa', 'Assab'],
  'EE': ['Tallinn', 'Tartu', 'Narva', 'Pärnu'],
  'SZ': ['Mbabane', 'Manzini', 'Big Bend', 'Malkerns'],
  'ET': ['Addis Ababa', 'Gondar', 'Mekelle', 'Adama', 'Hawassa', 'Dire Dawa', 'Bahir Dar', 'Jimma', 'Dessie', 'Jijiga'],
  'FJ': ['Suva', 'Nadi', 'Lautoka', 'Labasa'],
  'FI': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu'],
  'FR': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
  'GA': ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem'],
  'GM': ['Banjul', 'Serekunda', 'Brikama', 'Bakau'],
  'GE': ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi'],
  'DE': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'],
  'GH': ['Accra', 'Kumasi', 'Tamale', 'Takoradi', 'Cape Coast'],
  'GR': ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa'],
  'GD': ["St. George's", 'Gouyave', 'Grenville', 'Victoria'],
  'GT': ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango'],
  'GN': ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia'],
  'GW': ['Bissau', 'Bafatá', 'Gabú', 'Bissorã'],
  'GY': ['Georgetown', 'Linden', 'New Amsterdam', 'Anna Regina'],
  'HT': ['Port-au-Prince', 'Carrefour', 'Delmas', 'Pétion-Ville', 'Gonaïves'],
  'HN': ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'Choloma'],
  'HU': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs'],
  'IS': ['Reykjavik', 'Kópavogur', 'Hafnarfjörður', 'Akureyri'],
  'IN': ['Mumbai', 'Delhi', 'Bangalore', 'Kolkata', 'Chennai', 'Hyderabad', 'Pune', 'Ahmedabad', 'Surat', 'Lucknow'],
  'ID': ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Bekasi', 'Semarang', 'Tangerang', 'Depok', 'Makassar', 'Palembang'],
  'IR': ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz', 'Tabriz', 'Qom', 'Ahvaz', 'Kermanshah', 'Urmia'],
  'IQ': ['Baghdad', 'Mosul', 'Basra', 'Erbil', 'Kirkuk', 'Sulaymaniyah', 'Hillah', 'Karbala', 'Najaf', 'Ramadi'],
  'IE': ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford'],
  'IL': ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva'],
  'IT': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania'],
  'JM': ['Kingston', 'Montego Bay', 'Spanish Town', 'Portmore'],
  'JP': ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kyoto', 'Kawasaki', 'Saitama'],
  'JO': ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Aqaba'],
  'KZ': ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda', 'Aktobe'],
  'KE': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
  'KI': ['Tarawa', 'Betio', 'Bikenibeu'],
  'KW': ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'Salmiya'],
  'KG': ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol'],
  'LA': ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang'],
  'LV': ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava'],
  'LB': ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Byblos'],
  'LS': ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Hlotse'],
  'LR': ['Monrovia', 'Gbarnga', 'Buchanan', 'Kakata'],
  'LY': ['Tripoli', 'Benghazi', 'Misrata', 'Tarhuna', 'Bayda'],
  'LI': ['Schaan', 'Vaduz', 'Triesen', 'Balzers'],
  'LT': ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai'],
  'LU': ['Luxembourg', 'Esch-sur-Alzette', 'Differdange', 'Dudelange'],
  'MG': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga'],
  'MW': ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'],
  'MY': ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Johor Bahru', 'Malacca City', 'Kota Kinabalu', 'Alor Setar', 'Kuantan'],
  'MV': ['Malé', 'Hulhumalé', 'Addu City', 'Fuvahmulah'],
  'ML': ['Bamako', 'Sikasso', 'Mopti', 'Koutiala'],
  'MT': ['Valletta', 'Birkirkara', 'Mosta', 'Qormi'],
  'MH': ['Majuro', 'Ebeye', 'Rairok'],
  'MR': ['Nouakchott', 'Nouadhibou', 'Kiffa', 'Kaédi'],
  'MU': ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe'],
  'MX': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Juárez', 'Zapopan', 'Mérida', 'Chihuahua'],
  'FM': ['Palikir', 'Weno', 'Colonia'],
  'MD': ['Chisinau', 'Tiraspol', 'Bălți', 'Bender'],
  'MC': ['Monaco', 'Monte Carlo', 'La Condamine'],
  'MN': ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Choibalsan'],
  'ME': ['Podgorica', 'Nikšić', 'Pljevlja', 'Bijelo Polje'],
  'MA': ['Casablanca', 'Rabat', 'Fes', 'Marrakesh', 'Agadir', 'Tangier', 'Meknes', 'Oujda', 'Kenitra', 'Tetouan'],
  'MZ': ['Maputo', 'Matola', 'Nampula', 'Beira', 'Chimoio'],
  'MM': ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine'],
  'NA': ['Windhoek', 'Rundu', 'Walvis Bay', 'Oshakati'],
  'NR': ['Yaren', 'Denigomodu', 'Aiwo'],
  'NP': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Birgunj'],
  'NL': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen'],
  'NZ': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga'],
  'NI': ['Managua', 'León', 'Masaya', 'Tipitapa'],
  'NE': ['Niamey', 'Zinder', 'Maradi', 'Agadez'],
  'NG': ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City', 'Kaduna', 'Maiduguri', 'Zaria', 'Aba'],
  'KP': ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo'],
  'MK': ['Skopje', 'Bitola', 'Kumanovo', 'Prilep'],
  'NO': ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen'],
  'OM': ['Muscat', 'Seeb', 'Salalah', 'Bawshar', 'Sohar'],
  'PK': ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 'Peshawar', 'Multan', 'Hyderabad', 'Islamabad', 'Quetta'],
  'PW': ['Ngerulmud', 'Koror', 'Melekeok'],
  'PS': ['Gaza City', 'Hebron', 'Nablus', 'Ramallah', 'Khan Yunis'],
  'PA': ['Panama City', 'San Miguelito', 'Tocumen', 'David'],
  'PG': ['Port Moresby', 'Lae', 'Arawa', 'Mount Hagen'],
  'PY': ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque'],
  'PE': ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Cusco', 'Iquitos', 'Huancayo', 'Chimbote', 'Pucallpa'],
  'PH': ['Manila', 'Quezon City', 'Davao City', 'Caloocan', 'Cebu City', 'Zamboanga City', 'Taguig', 'Antipolo', 'Pasig', 'Cagayan de Oro'],
  'PL': ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice'],
  'PT': ['Lisbon', 'Porto', 'Amadora', 'Braga', 'Setúbal'],
  'QA': ['Doha', 'Al Rayyan', 'Umm Salal Muhammad', 'Al Wakrah'],
  'RO': ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov', 'Galați', 'Ploiești', 'Oradea'],
  'RU': ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Chelyabinsk', 'Samara', 'Omsk', 'Rostov-on-Don'],
  'RW': ['Kigali', 'Gisenyi', 'Ruhengeri', 'Butare'],
  'KN': ['Basseterre', 'Charlestown', 'Saint Paul\'s'],
  'LC': ['Castries', 'Vieux Fort', 'Micoud', 'Soufrière'],
  'VC': ['Kingstown', 'Georgetown', 'Byera Village'],
  'WS': ['Apia', 'Vaitele', 'Faleula'],
  'SM': ['San Marino', 'Serravalle', 'Borgo Maggiore'],
  'ST': ['São Tomé', 'Santo Amaro', 'Neves'],
  'SA': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Taif', 'Khobar', 'Tabuk', 'Buraidah', 'Khamis Mushait'],
  'SN': ['Dakar', 'Touba', 'Thiès', 'Rufisque', 'Kaolack'],
  'RS': ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac'],
  'SC': ['Victoria', 'Anse Royale', 'Beau Vallon'],
  'SL': ['Freetown', 'Bo', 'Kenema', 'Koidu Town'],
  'SG': ['Singapore'],
  'SK': ['Bratislava', 'Košice', 'Prešov', 'Žilina'],
  'SI': ['Ljubljana', 'Maribor', 'Celje', 'Kranj'],
  'SB': ['Honiara', 'Auki', 'Gizo', 'Noro'],
  'SO': ['Mogadishu', 'Hargeisa', 'Merca', 'Berbera', 'Kismayo'],
  'ZA': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Soweto', 'Bloemfontein', 'Pietermaritzburg', 'East London', 'Nelspruit'],
  'KR': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Yongin', 'Goyang'],
  'SS': ['Juba', 'Wau', 'Malakal', 'Yei'],
  'ES': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao'],
  'LK': ['Colombo', 'Dehiwala-Mount Lavinia', 'Moratuwa', 'Sri Jayawardenepura Kotte', 'Negombo', 'Kandy', 'Kalmunai', 'Vavuniya', 'Galle', 'Trincomalee'],
  'SD': ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala', 'El Obeid'],
  'SR': ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie'],
  'SE': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås'],
  'CH': ['Zürich', 'Geneva', 'Basel', 'Lausanne', 'Bern'],
  'SY': ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama'],
  'TW': ['Taipei', 'New Taipei City', 'Kaohsiung', 'Taichung', 'Tainan'],
  'TJ': ['Dushanbe', 'Khujand', 'Bokhtar', 'Kulob'],
  'TZ': ['Dodoma', 'Dar es Salaam', 'Mwanza', 'Arusha', 'Mbeya'],
  'TH': ['Bangkok', 'Nonthaburi', 'Nakhon Ratchasima', 'Chiang Mai', 'Hat Yai', 'Udon Thani', 'Pak Kret', 'Khon Kaen', 'Ubon Ratchathani', 'Nakhon Si Thammarat'],
  'TL': ['Dili', 'Same', 'Baucau', 'Maliana'],
  'TG': ['Lomé', 'Sokodé', 'Kara', 'Atakpamé'],
  'TO': ["Nuku'alofa", 'Neiafu', 'Haveluloto'],
  'TT': ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima'],
  'TN': ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte'],
  'TR': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Antalya', 'Kayseri', 'Mersin'],
  'TM': ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary'],
  'TV': ['Funafuti', 'Vaiaku'],
  'UG': ['Kampala', 'Nansana', 'Kira', 'Ssabagabo'],
  'UA': ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Kryvyi Rih', 'Mykolaiv', 'Mariupol'],
  'AE': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman'],
  'GB': ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Leeds', 'Sheffield', 'Edinburgh', 'Bristol', 'Cardiff'],
  'US': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
  'UY': ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú'],
  'UZ': ['Tashkent', 'Samarkand', 'Namangan', 'Andijan', 'Bukhara'],
  'VU': ['Port Vila', 'Luganville', 'Norsup'],
  'VA': ['Vatican City'],
  'VE': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay'],
  'VN': ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Haiphong', 'Can Tho', 'Bien Hoa', 'Nha Trang', 'Hue', 'Vung Tau', 'Quy Nhon'],
  'YE': ["Sana'a", 'Aden', 'Taiz', 'Al Hudaydah', 'Ibb'],
  'ZM': ['Lusaka', 'Ndola', 'Kitwe', 'Kabwe', 'Chingola'],
  'ZW': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare'],
};

export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find(country => country.code === code);
};

export const getCitiesForCountry = (countryCode: string): string[] => {
  // Return the cities array, or an empty array if the country code doesn't exist.
  return citiesByCountry[countryCode] || [];
};

export const searchCountries = (query: string): Country[] => {
  if (!query) return countries;
  
  const lowercaseQuery = query.toLowerCase();
  return countries.filter(country => 
    country.name.toLowerCase().includes(lowercaseQuery) ||
    country.code.toLowerCase().includes(lowercaseQuery)
  );
};

export const searchCities = (countryCode: string, query: string): string[] => {
  const cities = getCitiesForCountry(countryCode);
  if (!query) return cities;
  
  const lowercaseQuery = query.toLowerCase();
  return cities.filter(city => 
    city.toLowerCase().includes(lowercaseQuery)
  );
};